### ISSUE TITLE
Need to replace Code Helper to run code

### ISSUE THREAD

**Issue by InvisibleCat123** [InvisibleCat123/ChickCoder-InvisibleCat-Collabs#1]
Please fix ASAP

**Comment by ChickCoder123** [comment]
It works like this:
`//Paste this in to your Code Helper (javascript section) and click "Apply"
//For some strange reason, you must destroy the Code Helper (click Backspace while pointing at it) and place it down again for this to go in effect
var _0x4109=["\x73\x65\x74\x50\x72\x6F\x64\x75\x63\x74\x51\x75\x61\x6E\x74\x69\x74\x79","\x61\x73\x73\x65\x74\x73","\x63\x69\x74\x79","\x5F\x63\x6F\x6E\x74\x65\x78\x74"];window[_0x4109[3]][_0x4109[2]][_0x4109[1]][_0x4109[0]](0,1,Infinity);window[_0x4109[3]][_0x4109[2]][_0x4109[1]][_0x4109[0]](0,2,Infinity);window[_0x4109[3]][_0x4109[2]][_0x4109[1]][_0x4109[0]](0,3,Infinity);window[_0x4109[3]][_0x4109[2]][_0x4109[1]][_0x4109[0]](0,4,Infinity);window[_0x4109[3]][_0x4109[2]][_0x4109[1]][_0x4109[0]](0,5,Infinity);window[_0x4109[3]][_0x4109[2]][_0x4109[1]][_0x4109[0]](0,6,Infinity);window[_0x4109[3]][_0x4109[2]][_0x4109[1]][_0x4109[0]](0,7,Infinity);window[_0x4109[3]][_0x4109[2]][_0x4109[1]][_0x4109[0]](0,8,Infinity)
_context.city.ui.updateInventory()`
